package org.example.nextstepbackend.enums;

public enum ActionType {
  CREATE_CARD,
  UPDATE_CARD,
  DELETE_CARD,
  MOVE_CARD,
  ADD_LABEL,
  CREATE_CHECKLIST,
  ADD_CHECKLIST_ITEM,
  COMPLETE_CHECKLIST_ITEM,
  DELETE_CHECKLIST,
  ADD_ATTACHMENT,
  DELETE_ATTACHMENT,
  ADD_LABEL_TO_CARD,
  REMOVE_LABEL_FROM_CARD
}
